// Rule status progression: active → warning → broken
export type RuleStatus = 'active' | 'warning' | 'broken' | 'disabled';

// How the selector was derived (for stability ranking)
export type SelectorStrategy =
  | 'data-attribute'
  | 'aria-label'
  | 'href-pattern'
  | 'id'
  | 'semantic-class'
  | 'custom-element'
  | 'structural';

// Individual CSS rule generated by LLM
export interface CSSRule {
  id: string;
  userRequest: string;
  generatedCSS: string;
  selectors: string[];
  selectorStrategies: SelectorStrategy[];
  enabled: boolean;
  status: RuleStatus;
  failureCount: number;
  confidence: number;
  createdAt: number;
  updatedAt: number;
  lastValidated: number | null;
}

// Rules grouped by domain
export interface DomainRules {
  domain: string;
  rules: CSSRule[];
  lastAccessed: number;
}

// User settings
export interface UserSettings {
  llmProvider: 'openai' | 'anthropic';
  notifyOnFailure: boolean;
  theme: 'light' | 'dark' | 'system';
}

// Root storage schema
export interface StorageSchema {
  domains: Record<string, DomainRules>;
  settings: UserSettings;
}

// LLM response format
export interface LLMResponse {
  success: boolean;
  css?: string;
  selectors?: string[];
  explanation?: string;
  confidence?: number;
  fallbackSelectors?: string[];
  error?: string;
  suggestion?: string;
}

// Message types for chrome.runtime.sendMessage
export type MessageType =
  | 'GET_CSS_FOR_DOMAIN'
  | 'GET_RULES_FOR_DOMAIN'
  | 'GET_ALL_RULES'
  | 'GENERATE_CSS'
  | 'REGENERATE_RULE'
  | 'UPDATE_RULE'
  | 'DELETE_RULE'
  | 'INJECT_CSS'
  | 'RULE_VALIDATION_FAILURE'
  | 'CHECK_API_KEY'
  | 'SAVE_API_KEY'
  | 'GET_SETTINGS'
  | 'SAVE_SETTINGS'
  | 'SERIALIZE_DOM';

export interface Message {
  type: MessageType;
  [key: string]: unknown;
}

// Validation result from content script
export interface ValidationResult {
  ruleId: string;
  selector: string;
  status: 'valid' | 'invalid' | 'partial';
  matchCount: number;
  hiddenCount: number;
}

// Serialized DOM node (token-efficient format)
export interface SerializedNode {
  tag: string;
  id?: string;
  classes?: string[];
  dataAttrs?: Record<string, string>;
  ariaLabel?: string;
  role?: string;
  href?: string;
  text?: string;
  children?: SerializedNode[];
}
